plan:
  task:
    env_id: "pusht"
    env:
      with_velocity: true
      with_target: true
      add_noise: 0
      noise_std: [0.5, 0.5]
      render_size: 96
    init_goal:
      source: "dataset"
      dataset:
        zarr_path: "synthetic/pusht_synth_planning_translation_100_len30.zarr"
        split: "train"
        split_ratio: null
        trajectory_len: 30
        seed: 45 #12 #45 #12 #10
        reconstruct_goal_state: 3
