env_id: "swm/PushT-v1"
image_shape: 96
max_episode_steps: 100
num_envs: 4
episodes: 100
seed: 0
output_path: "data/pusht_swm.h5"
goal_conditioned: true
env_kwargs: {}
policy:
  import_path: null

restore:
  import_path: null
