sim:
  env_id: "pusht"
  seq_len: 10
  var_threshold: 100000
  batch_size: 1
  render_interval: 0.1
  # Angle representation follows training config: data.use_sincos
  env_kwargs: {with_velocity: true, with_target: true }    # any gym.make kwargs
  use_planner: true
  planner_kwargs: {pop_size: 128, elite_frac: 0.1, n_iter: 4, use_gt: false, closed_loop: false, agg_mode: "average", n_impute: 1}
  checkpoint_dir: "masked-dynamics-experiment_20250506_022524"
  reset_state: false
