
# 256
# plan:
#   budget:
#     max_env_steps: 50
#   planner:
#     horizon: 20
#     replan_every: 20
#     cem:
#       pop_size: 2000
#       elite_frac: 0.01
#       n_iter: 10
#       init_std: 1
#       # If true (and init_goal provides meta.actions), seed CEM with that trajectory on replan 0.
#       inject_dataset_gt_actions: false
#       warm_start: true
#       action_low: null
#       action_high: null

# plan:
#   budget:
#     max_env_steps: 50
#   planner:
#     horizon: 20
#     replan_every: 20
#     cem:
#       pop_size: 2000
#       elite_frac: 0.01
#       n_iter: 5
#       init_std: 1
#       # If true (and init_goal provides meta.actions), seed CEM with that trajectory on replan 0.
#       inject_dataset_gt_actions: false
#       warm_start: true
#       action_low: null
#       action_high: null

plan:
  budget:

    max_env_steps: 100
  planner:
    horizon: 20
    replan_every: 20
    cem:
      pop_size: 5000
      elite_frac: 0.1
      n_iter: 10
      init_std: 0.2 #1
      # If true (and init_goal provides meta.actions), seed CEM with that trajectory on replan 0.
      inject_dataset_gt_actions: false
      warm_start: false
      action_low: null
      action_high: null
